require: rubocop-rspec

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/internal/bin/*'
    - 'spec/internal/db/schema.rb'

Metrics/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/hydra/works/services/generic_file/add_file_to_generic_file.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/hydra/works/services/generic_file/add_file_to_generic_file.rb

Metrics/MethodLength:
  Exclude:
    - lib/hydra/works/services/generic_file/add_file_to_generic_file.rb
    - lib/hydra/works/models/concerns/generic_file/virus_check.rb

Metrics/AbcSize:
  Exclude:
    - lib/hydra/works/services/generic_file/add_file_to_generic_file.rb
    - lib/hydra/works/services/generic_file/full_text_extraction_service.rb	
    - lib/hydra/works/models/concerns/generic_file/mime_types.rb
    - lib/hydra/works/models/concerns/generic_file/virus_check.rb

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - 'spec/hydra/works/models/concerns/generic_file/characterization_spec.rb'

