---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@dev:solr_core
jobs:
  test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    steps:
      - run: 'sudo apt-get update && sudo apt-get install clamav'
      - run: 'sudo freshclam'
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-works
      - samvera/install_solr_core
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.3
          rails_version: 5.2.3
      - test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.5
          rails_version: 5.2.3
      - test:
          name: ruby2-4_rails5-2
          ruby_version: 2.4.6
          rails_version: 5.2.3
      - test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.3
          rails_version: 5.1.7
      - test:
          name: ruby2-5_rails5-1
          ruby_version: 2.5.5
          rails_version: 5.1.7
      - test:
          name: ruby2-4_rails5-1
          ruby_version: 2.4.6
          rails_version: 5.1.7
